[project]
name = "secret-store"
version = "0.0.1"
dependencies = [
    "paramiko>=2.11.0,<2.12",
]
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3.10",
]

[tool.setuptools.packages.find]
where = ["src"]

[project.scripts]
secret-store = "secretstore.bin.cli:main"